version: '{build}'  
os: Visual Studio 2017
pull_requests:  
  do_not_increment_build_number: true
branches:  
  only:
  - development
  - master
nuget:  
  disable_publish_on_pr: true
build_script:  
- ps: .\Build.ps1
test: off  
artifacts:  
- path: .\**\artifacts\**\Serilog.*.nupkg
  name: NuGet
deploy:  
- provider: NuGet
  name: production
  api_key:
    secure: BAtH8CvaSmfHl50sCLITa9KxPfJoL3OwazW6hCRUefLldlTdFyKwU69RRAuc4vko
  on:
    branch: master
    appveyor_repo_tag: true
